version: "3"

services:
  nginx:
    image: "nginx"
    container_name: "nginx"
    user: root
    privileged: true
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./web:/home/web:ro"
      - "./nginx/:/etc/nginx/:ro"
      - "./cert:/etc/cert"
    restart: always

  xui:
    image: "enwaiax/x-ui:latest"
    container_name: "x-ui"
    network_mode: "host"
    # 默认配置
    # 端口：54321
    # 账号：admin
    # 密码：admin
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./data:/etc/x-ui"
      - "./cert:/root/cert"
    restart: always

  shadowsocks:
    image: "shadowsocks/shadowsocks-libev"
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - SERVER_ADDR=0.0.0.0  # 监听地址
      - SERVER_PORT=8388  # 监听端口
      - METHOD=aes-256-gcm  # 加密方式
      - PASSWORD=o0o2022  # 登陆密码
      - TIMEOUT=600  # 超时时间
    restart: always

